version: '3.9'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./src:/var/www
  aoru-kun-app:
    image: aoru-kun-app:latest
    ports:
      - '80:8080'
  db:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aorukun
