version: '3.9'

services:
  app:
    build: ./docker/app
    volumes:
      - ./src:/var/www/html
  db:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aorukun
  nginx:
    image: nginx:1.18
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
